version: '3'
services:
  db:
    env_file:
      - ./.env.prod
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  web:
    env_file:
      - ./.env.prod
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - DATABASE_HOST=db
      - RAILS_ENV=production
      - RAILS_LOG_TO_STDOUT=true
    volumes:
      - .:/myapp
      - web_gem_cache:/usr/local/bundle
      - web_npm_cache:/myapp/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  web_gem_cache:
  web_npm_cache:
